project:
  type: website

website:
  title: "João Afonso Poester-Carvalho"
  site-url: https://afonsopoester.github.io/
  navbar:
    background: info
    right:
      - href: 1_MAIN.qmd
        text: Home
      - href: 2_Blog.qmd
        text: Portfolio
      - href: 1_Publications.qmd
        text: Publications
      - href: 3_CV.qmd
        text: CV
      - icon: github
        href: "https://github.com/afonsopoester"
      - text: "{{< iconify simple-icons researchgate >}}"
        href: "https://www.researchgate.net/profile/Joao-Afonso-Poester-Carvalho-2"
      - text: "{{< iconify academicons google-scholar-square >}}"
        href: "https://scholar.google.com.br/citations?user=O8awK9kAAAAJ&hl=pt-BR"
        
        
  page-footer: |
      This website was built using Quarto!
      
format:
  html:
    theme: 
      - cosmo
      - styles.scss




